# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTool@0
  inputs:
    version: '1.2.4'
# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Azure subscription 1 (cf06eda7-48ad-45ca-a32d-9eec96042b9f)'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#      az login --service-principal -u $(APPID) -p $(PASSWORD) --tenant $(TENANT)
     
- script: |
        terraform init 
        export TF_VAR_appId=$(APPID)
        export TF_VAR_password=$(PASSWORD)
        export TF_VAR_subscription_id=$(SUBSCRIPTION_ID)
        export TF_VAR_tenant_id=$(TENANT_ID)
         export TF_VAR_client_secret=$(CLIENT_SECRET)
        terraform plan -var 'appId=$(APPID)' -var 'password=$(PASSWORD)'
  displayName: 'Initialize terraform '

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'