
parameters:
  environment: "$(environment)"
  template_directory: "$(template_directory)"
  subscription_id: "$(subscriptionid)"
  client_id: "$(clientid)"
  client_secret: "$(clientsecret)"
  tenant_id: "$(tenantid)"

jobs:
  - job: TerraformPlan
    pool: Azure Pipelines
    timeoutInMinutes: 240
    steps:
      - task: Bash@3
        name: TerraformPlan
        displayName: "Terraform Plan"
        inputs:
          workingDirectory: "$(Pipeline.Workspace)/s/${{ parameters.template_directory }}"
          targetType: "inline"
          script: |
            cat <<EOF > auth.sh
            export ARM_SUBSCRIPTION_ID="${{ parameters.subscription_id }}"
            export ARM_CLIENT_ID="${{ parameters.client_id }}"
            export ARM_CLIENT_SECRET="${{ parameters.client_secret }}"
            export ARM_TENANT_ID="${{ parameters.tenant_id }}"
            EOF
            terraform -v

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(Pipeline.Workspace)/s/terraform"
          artifact: "drop"

